name: test

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run action
      id: run_action
      uses: ./
      with:
        my_input: 'World'

    - name: log action output
      run: echo ${{steps.run_action.outputs.my_output}}
